name: Submit Bioconda Recipe

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動実行を許可

jobs:
  submit-bioconda:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: meta.yamlの自動生成
        run: |
          mkdir -p bioconda-recipes/recipes/cdskit
          cat <<EOF > bioconda-recipes/recipes/cdskit/meta.yaml
          package:
            name: "cdskit"
            version: "1.0.0"

          source:
            url: "https://example.com/your-package.tar.gz"
            sha256: "your_sha256_hash"

          build:
            number: 0
            script: "build.sh"

          requirements:
            build:
              - python
            run:
              - python

          test:
            imports:
              - cdskit

          about:
            home: "https://github.com/your-repo/cdskit"
            license: "MIT"
            summary: "A toolkit for CDS analysis"
          EOF

      - name: BiocondaのCIテスト
        run: |
          cd bioconda-recipes
          conda install -y -c conda-forge conda-build
          conda build recipes/cdskit

      - name: GitHubへプッシュ & PR作成
        env:
          GITHUB_TOKEN: ${{ secrets.BIOCONDA_PAT }}
        run: |
          cd bioconda-recipes
          git config --global user.email "usuke.a62@gmail.com"
          git config --global user.name "kamome1201"
          git add recipes/cdskit/meta.yaml
          git commit -m "Auto-generate meta.yaml and add cdskit recipe"
          git push fork add-your-package
          gh pr create --base main --head add-your-package --title "Add cdskit" --body "Auto-generated Bioconda recipe"
