on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  submit-bioconda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: cdskit
          fetch-depth: 0

      - name: フォークしたbioconda-recipesをチェックアウト
        uses: actions/checkout@v4
        with:
          repository: kamome1201/bioconda-recipes
          token: ${{ secrets.BIOCONDA_PAT }}
          path: bioconda-recipes

      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          python-version: "3.10"

      - name: 最新版レシピ作成（vなしタグ対応）
        shell: bash -l {0}
        run: |
          VERSION=$(git -C cdskit describe --tags --abbrev=0)
          URL="https://github.com/kamome1201/cdskit/archive/refs/tags/${VERSION}.tar.gz"
          SHA256=$(curl -L ${URL} | sha256sum | cut -d' ' -f1)
          export VERSION URL SHA256
      
          mkdir -p bioconda-recipes/recipes/cdskit
      
          cat <<EOF > bioconda-recipes/recipes/cdskit/meta.yaml
          {% set name = "cdskit" %}
          {% set version = "${VERSION}" %}
      
          package:
            name: '{{ name|lower }}'
            version: '{{ version }}'
      
          source:
            url: "${URL}"
            sha256: "${SHA256}"
      
          build:
            number: 0
            noarch: python
            script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"
      
          requirements:
            host:
              - python >=3.8
              - pip
            run:
              - python >=3.8
      
          test:
            imports:
              - cdskit
      
          about:
            home: "https://github.com/kamome1201/cdskit"
            license: "MIT"
            summary: "CDSKIT processes DNA sequences, especially protein-coding sequences."
          EOF

      - name: PR作成
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BIOCONDA_PAT }}
          path: bioconda-recipes
          commit-message: "Add/update cdskit recipe v${{ env.VERSION }}"
          branch: "add-cdskit-v${{ env.VERSION }}"
          base: master
          title: "Add/update cdskit recipe v${{ env.VERSION }}"
