name: Submit Bioconda Recipe

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動実行を許可

jobs:
  submit-bioconda:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 後でトークンを明示的に設定するため

      - name: Bioconda 環境のセットアップ
        run: |
          sudo apt-get update && sudo apt-get install -y git
          conda create -n bioconda -y -c conda-forge -c bioconda bioconda-utils conda-build
          echo "source activate bioconda" >> ~/.bashrc
          source ~/.bashrc

      - name: meta.yamlの自動生成
        run: |
          mkdir -p recipes/cdskit
          ls -l bioconda-recipes/recipes
          cat <<EOF > recipes/cdskit/meta.yaml
          {% set name = "cdskit" %}
          {% set version = "0.1.0" %}
          
          package:
            name: '{{ name|lower }}'
            version: '{{ version }}'

          source:
            url: "https://github.com/kamome1201/cdskit/archive/refs/tags/0.1.0.tar.gz"
            sha256: "61b6a2b402a21427f4181ddaff6d9f635ab14f0a44c6bfe1958a02061f20130e"

          build:
            number: 0
            noarch: python
            entry_points:
              - biotdg = biotdg:main
            script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"

          requirements:
            build:
              - python
            run:
              - python

          test:
            imports:
              - cdskit

          about:
            home: "https://github.com/kamome1201/cdskit"
            license: "MIT"
            summary: "CDSKIT is a Python program that processes DNA sequences, especially protein-coding sequences."
          EOF

      - name: BiocondaのCIテスト (`bioconda-utils build` を使用)
        run: |
          source activate bioconda
          bioconda-utils build --packages recipes/cdskit --docker --mulled-test

      - name: Biocondaフォークリポジトリへプッシュ & PR作成
        env:
          GITHUB_TOKEN: ${{ secrets.BIOCONDA_PAT }}
        run: |
          git config --global user.email "usuke.a62@gmail.com"
          git config --global user.name "kamome1201"
          
          # Fork したリポジトリをセットアップ
          git remote add fork https://github.com/kamome1201/bioconda-recipes.git
          
          # 新しいブランチを作成
          git checkout -b add-cdskit
          git add recipes/cdskit/meta.yaml
          git commit -m "Auto-generate meta.yaml and add cdskit recipe"
          git push fork add-cdskit

          # PRの作成
          GH_TOKEN=${{ secrets.BIOCONDA_PAT }} gh pr create \
            --base main \
            --head kamome1201:add-cdskit \
            --title "Add cdskit" \
            --body "Auto-generated Bioconda recipe"
